# Generated by Django 6.1 on 2026-08-14 08:44

from django.db import migrations


def create_default_copies(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    BookCopy = apps.get_model('books', 'BookCopy')
    for book in Book.objects.all():
        BookCopy.objects.get_or_create(
            book=book,
            copy_number='001',
            defaults={'status': 'available'}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_member_bookcopy_borrowrecord'),
    ]

    operations = [
        migrations.RunPython(create_default_copies, migrations.RunPython.noop),
    ]